# AUTO-GENERATED by spnl-erb — DO NOT EDIT
# mode: stateless (class method + local vars, no ivar)
# 利用: AboutView.render(site_name, site_tagline, stats_posts, stats_comments, founded, tech, template_size_bytes, binary_size_kb)
module AboutView
  def self.render(site_name, site_tagline, stats_posts, stats_comments, founded, tech, template_size_bytes, binary_size_kb)
    _out = ""
    _out = _out + "<section>\n  <h1>About "
    _out = _out + (site_name).to_s
    _out = _out + "</h1>\n  <p>"
    _out = _out + (site_tagline).to_s
    _out = _out + "</p>\n\n  <h2>Stats</h2>\n  <ul>\n    <li>Total posts: <strong>"
    _out = _out + (stats_posts).to_s
    _out = _out + "</strong></li>\n    <li>Total comments: <strong>"
    _out = _out + (stats_comments).to_s
    _out = _out + "</strong></li>\n    <li>Founded: <strong>"
    _out = _out + (founded).to_s
    _out = _out + "</strong></li>\n  </ul>\n\n  <h2>Tech stack</h2>\n  <ul>\n"
    tech.each do |item|
    _out = _out + "    <li>"
    _out = _out + (item).to_s
    _out = _out + "</li>\n"
    end
    _out = _out + "  </ul>\n\n  <h2>Build size</h2>\n  <p>This page was rendered from <strong>"
    _out = _out + (template_size_bytes).to_s
    _out = _out + "</strong> bytes\n  of ERB and is now part of a <strong>"
    _out = _out + (binary_size_kb).to_s
    _out = _out + " KB</strong> single-binary\n  HTTP server.</p>\n</section>\n"
    _out
  end
end
