# AUTO-GENERATED by spnl-erb — DO NOT EDIT
# mode: stateless (class method + local vars, no ivar)
# 利用: LayoutView.render(page_title, site_name, site_tagline, active_nav, content, year, generated_at, render_count)
module LayoutView
  def self.render(page_title, site_name, site_tagline, active_nav, content, year, generated_at, render_count)
    _out = ""
    _out = _out + "<!DOCTYPE html>\n<html lang=\"ja\">\n<head>\n  <meta charset=\"utf-8\">\n  <title>"
    _out = _out + (page_title).to_s
    _out = _out + " — "
    _out = _out + (site_name).to_s
    _out = _out + "</title>\n  <meta name=\"description\" content=\""
    _out = _out + (site_tagline).to_s
    _out = _out + "\">\n  <style>\n    body { font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif;\n           max-width: 720px; margin: 2em auto; padding: 0 1em; line-height: 1.6;\n           color: #222; background: #fafafa; }\n    nav { display: flex; gap: 1.5em; padding-bottom: 1em; border-bottom: 2px solid #333; margin-bottom: 2em; }\n    nav a { color: #07c; text-decoration: none; font-weight: 600; }\n    nav a.active { color: #c33; }\n    h1 { margin: 0.5em 0 0.2em; }\n    h1 a { color: inherit; text-decoration: none; }\n    .meta { color: #888; font-size: 0.9em; margin-bottom: 1.5em; }\n    .tag { display: inline-block; padding: 0.1em 0.6em; margin: 0 0.2em;\n           background: #eef; color: #339; border-radius: 3px; font-size: 0.85em; }\n    article { background: white; padding: 1.5em; border-radius: 6px;\n              border: 1px solid #ddd; margin-bottom: 1.5em; }\n    article header { margin-bottom: 1em; }\n    .comment { background: #f8f8f8; padding: 0.8em 1em; border-left: 3px solid #ccc;\n               margin: 0.5em 0; border-radius: 0 3px 3px 0; }\n    .comment .meta { font-size: 0.85em; margin: 0 0 0.3em; }\n    footer { margin-top: 3em; padding-top: 1em; border-top: 1px solid #ddd;\n             color: #888; font-size: 0.85em; text-align: center; }\n    .stats { display: flex; gap: 1em; color: #666; font-size: 0.9em; }\n    .empty { color: #888; font-style: italic; }\n  </style>\n</head>\n<body>\n  <nav>\n    <a href=\"/\" class=\""
    _out = _out + (active_nav == "home" ? "active" : "").to_s
    _out = _out + "\">Home</a>\n    <a href=\"/archives\" class=\""
    _out = _out + (active_nav == "archives" ? "active" : "").to_s
    _out = _out + "\">Archives</a>\n    <a href=\"/about\" class=\""
    _out = _out + (active_nav == "about" ? "active" : "").to_s
    _out = _out + "\">About</a>\n  </nav>\n\n  "
    _out = _out + (content).to_s
    _out = _out + "\n\n  <footer>\n    <p>© "
    _out = _out + (year).to_s
    _out = _out + " "
    _out = _out + (site_name).to_s
    _out = _out + ". Built with\n    <a href=\"https://github.com/matz/spinel\">Spinel</a> +\n    <a href=\"https://github.com/gorin9/spnl-erb\">spnl-erb</a>.</p>\n    <p>Generated at "
    _out = _out + (generated_at).to_s
    _out = _out + ". Total render: "
    _out = _out + (render_count).to_s
    _out = _out + " view(s).</p>\n  </footer>\n</body>\n</html>\n"
    _out
  end
end
