# AUTO-GENERATED by spnl-erb — DO NOT EDIT
# mode: stateless (class method + local vars, no ivar)
# 利用: PostsIndexView.render(posts, total_count)
module PostsIndexView
  def self.render(posts, total_count)
    _out = ""
    _out = _out + "<section>\n  <h1>Latest posts</h1>\n  <p class=\"meta\">Showing "
    _out = _out + (posts.length).to_s
    _out = _out + " of "
    _out = _out + (total_count).to_s
    _out = _out + " posts</p>\n\n  "
    if posts.length == 0
    _out = _out + "  <p class=\"empty\">No posts yet — be the first to write!</p>\n  "
    else
    _out = _out + "  "
    i = 0
        posts.each do |p|
          i = i + 1
    _out = _out + "  <article>\n    <header>\n      <h1><a href=\"/posts/"
    _out = _out + (p.slug).to_s
    _out = _out + "\">"
    _out = _out + (p.title).to_s
    _out = _out + "</a></h1>\n      <p class=\"meta\">\n        by <strong>"
    _out = _out + (p.author).to_s
    _out = _out + "</strong>\n        · "
    _out = _out + (p.posted_date).to_s
    _out = _out + "\n        · "
    _out = _out + (p.reading_minutes).to_s
    _out = _out + " min read\n      </p>\n      <p>\n"
    p.tags.each do |t|
    _out = _out + "        <span class=\"tag\">#"
    _out = _out + (t).to_s
    _out = _out + "</span>\n"
    end
    _out = _out + "      </p>\n    </header>\n    <p>"
    _out = _out + (p.excerpt(160)).to_s
    _out = _out + "</p>\n    <p class=\"stats\">\n      <span>💬 "
    _out = _out + (p.comments_count).to_s
    _out = _out + " comments</span>\n      <span>👁 "
    _out = _out + (p.views).to_s
    _out = _out + " views</span>\n"
    if p.featured?
    _out = _out + "      <span>⭐ Featured</span>\n"
    end
    _out = _out + "    </p>\n  </article>\n"
    end
    _out = _out + "  "
    end
    _out = _out + "</section>\n"
    _out
  end
end
