# AUTO-GENERATED by spnl-erb — DO NOT EDIT
# mode: controller (reopen BlogController, ivar 直接参照)
# 利用 (controller 側):
#   class BlogController
#     def show
#       @posts = Post.all
#       @title = "Latest"
#       respond(render_posts_show)
#     end
#   end
class BlogController
  def render_posts_show
    _out = ""
    _out = _out + "<article>\n  <header>\n    <h1>"
    _out = _out + (@post.title).to_s
    _out = _out + "</h1>\n    <p class=\"meta\">\n      by <strong>"
    _out = _out + (@post.author).to_s
    _out = _out + "</strong>\n      · "
    _out = _out + (@post.posted_date).to_s
    _out = _out + "\n      · "
    _out = _out + (@post.reading_minutes).to_s
    _out = _out + " min read\n      · "
    _out = _out + (@post.views).to_s
    _out = _out + " views\n    </p>\n    <p>\n"
    @post.tags.each do |t|
    _out = _out + "      <span class=\"tag\">#"
    _out = _out + (t).to_s
    _out = _out + "</span>\n"
    end
    _out = _out + "    </p>\n  </header>\n\n  <div>\n    "
    _out = _out + (@post.body).to_s
    _out = _out + "\n  </div>\n\n  <p class=\"meta\">\n    Status:\n    "
    case @post.status
          when :published then status_label = "Published"
          when :draft     then status_label = "Draft (private)"
          when :archived  then status_label = "Archived"
          else status_label = "Unknown"
          end
    _out = _out + "    <strong>"
    _out = _out + (status_label).to_s
    _out = _out + "</strong>\n  </p>\n</article>\n\n<section>\n  <h2>Comments ("
    _out = _out + (@comments.length).to_s
    _out = _out + ")</h2>\n\n  "
    if @comments.length == 0
    _out = _out + "  <p class=\"empty\">No comments yet.</p>\n  "
    else
    @comments.each do |c|
    _out = _out + "  <div class=\"comment\">\n    <p class=\"meta\">\n      <strong>"
    _out = _out + (c.author).to_s
    _out = _out + "</strong>\n      · "
    _out = _out + (c.posted_at).to_s
    _out = _out + "\n"
    if c.edited?
    _out = _out + "      · <em>(edited)</em>\n"
    end
    _out = _out + "    </p>\n    <p>"
    _out = _out + (c.body).to_s
    _out = _out + "</p>\n  </div>\n"
    end
    _out = _out + "  "
    end
    _out = _out + "</section>\n"
    _out
  end
end
