# AUTO-GENERATED by spnl-router — DO NOT EDIT
# source: BlogController
module Router
  def self.dispatch(path)
    c = BlogController.new
    # action が render_xxx 内で @site_name 等を参照する前に
    # set_chrome を空 default で先に呼んで ivar を確定させる.
    # (Spinel は nil ivar アクセスで segfault するため必須)
    c.set_chrome("", "")
    body = ""
    nav  = ""
    case path
    when "/"
      body = c.index; nav = "home"
    when "/about"
      body = c.about; nav = "about"
    else
      if path.start_with?("/posts/")
        id = path[7, path.length].to_i
        body = c.show(id); nav = "posts"
      end
      return "404" if body == ""
    end
    c.set_chrome(nav, body)
    c.render_layout
  end
end
