# spnl-erb: ERB -> Spinel-friendly Ruby code compiler
#
# 設計:
# - ビルド時 (CRuby) に走る
# - 出力は Spinel が AOT-compile できる pure Ruby
# - eval / binding / +""/.freeze / <<  を使わない
#
# 文法対応:
#   literal text        -> _out = _out + "..."
#   <%= expr %>         -> _out = _out + (expr).to_s
#   <%   code %>        -> code (raw)
#   <%# comment %>      -> skip
#   <%- ... %>          -> trim leading newline of preceding literal
#   <% ... -%>          -> trim trailing newline of following literal

module SpnlErb
  VERSION = "0.1.0"

  # Compile ERB string to Spinel-friendly Ruby body (no class wrapper).
  def self.compile_body(template, var_name: "_out")
    tokens = tokenize(template)
    emit_body(tokens, var_name)
  end

  # Compile to a complete class. ivars in template come from `attrs`.
  #
  #   compile_class(tpl, class_name: "UsersIndexView", attrs: ["name", "items"])
  #
  # mode:
  #   :controller -> 既存 class を reopen して `def render_xxx` を足す (推奨, Rails 風)
  #                  Controller 内の `@var = Klass.all` で代入する限り Spinel OK.
  #   :stateless  -> module + class method, 局所変数のみ (Array<UserClass> を引数で
  #                  受け取る場合のみ安全)
  #   :instance   -> class + initialize + render (簡単な型のみ. Array<UserClass> 不可)
  def self.compile_class(template, class_name:, attrs: [], method_name: "render", mode: :stateless, target_class: nil)
    if mode == :controller
      body = compile_body(template)
      indented = body.split("\n").map { |l| "    " + l }.join("\n")
      tgt = target_class || "Controller"
      return <<~RUBY
        # AUTO-GENERATED by spnl-erb — DO NOT EDIT
        # mode: controller (reopen #{tgt}, ivar 直接参照)
        # 利用 (controller 側):
        #   class #{tgt}
        #     def show
        #       @posts = Post.all
        #       @title = "Latest"
        #       respond(#{method_name})
        #     end
        #   end
        class #{tgt}
          def #{method_name}
        #{indented}
          end
        end
      RUBY
    end
    # path -> render method name の helper: "users/index" -> "render_users_index"
    # (caller が method_name に直接渡してもよい)

    if mode == :stateless
      # template の @x を x に置換 (literal 内の @ は対象外)
      stripped_tokens = tokenize(template).map { |kind, content|
        if kind == TOK_EXPR || kind == TOK_CODE
          [kind, content.gsub(/@(\w+)/, '\1')]
        else
          [kind, content]
        end
      }
      body = emit_body(stripped_tokens)
      params = attrs.join(", ")
      indented = body.split("\n").map { |l| "    " + l }.join("\n")
      return <<~RUBY
        # AUTO-GENERATED by spnl-erb — DO NOT EDIT
        # mode: stateless (class method + local vars, no ivar)
        # 利用: #{class_name}.#{method_name}(#{params})
        module #{class_name}
          def self.#{method_name}(#{params})
        #{indented}
          end
        end
      RUBY
    end

    # mode: :instance — class + initialize + render (ivar 使用)
    body = compile_body(template)
    init_params = attrs.join(", ")
    init_assigns = attrs.map { |a| "      @#{a} = #{a}" }.join("\n")
    indented_body = body.split("\n").map { |l| "    " + l }.join("\n")

    <<~RUBY
      # AUTO-GENERATED by spnl-erb — DO NOT EDIT
      # mode: instance (ivar). Polymorphic Array<UserClass> in ivar SEGFAULTs in Spinel.
      class #{class_name}
        def initialize(#{init_params})
      #{init_assigns}
        end

        def #{method_name}
      #{indented_body}
        end
      end
    RUBY
  end

  # --- 内部: tokenizer ---

  TOK_LITERAL = :lit
  TOK_EXPR    = :expr
  TOK_CODE    = :code

  def self.tokenize(template)
    tokens = []
    i = 0
    n = template.length

    while i < n
      open_idx = template.index("<%", i)
      if open_idx.nil?
        tokens << [TOK_LITERAL, template[i..-1]]
        break
      end

      # literal までを emit
      if open_idx > i
        tokens << [TOK_LITERAL, template[i...open_idx]]
      end

      # tag 判定
      tag_start = open_idx + 2
      kind = TOK_CODE
      trim_left = false
      trim_right = false

      case template[tag_start]
      when "="
        kind = TOK_EXPR
        tag_start += 1
      when "#"
        kind = :comment
        tag_start += 1
      when "-"
        trim_left = true
        tag_start += 1
      end

      close_idx = template.index("%>", tag_start)
      raise "unclosed ERB tag at #{open_idx}" if close_idx.nil?

      content_end = close_idx
      if template[close_idx - 1] == "-"
        trim_right = true
        content_end = close_idx - 1
      end

      content = template[tag_start...content_end].strip

      if kind == TOK_EXPR
        tokens << [TOK_EXPR, content]
      elsif kind == TOK_CODE
        tokens << [TOK_CODE, content]
      end

      i = close_idx + 2

      # trim_right: 直後の literal の先頭改行を削る
      if trim_right && i < n && template[i] == "\n"
        i += 1
      end

      # trim_left: 直前の literal token の末尾改行を削る
      if trim_left && !tokens.empty? && tokens.last && tokens.last[0] == TOK_LITERAL
        prev = tokens.last[1]
        if prev.end_with?("\n")
          tokens.last[1] = prev.chomp
        end
      end
    end

    tokens
  end

  def self.emit_body(tokens, var = "_out")
    lines = ["#{var} = \"\""]
    tokens.each do |kind, content|
      case kind
      when TOK_LITERAL
        next if content.empty?
        lines << "#{var} = #{var} + #{content.inspect}"
      when TOK_EXPR
        lines << "#{var} = #{var} + (#{content}).to_s"
      when TOK_CODE
        lines << content
      end
    end
    lines << var
    lines.join("\n")
  end
end
