# spnl-erb: ERB -> Spinel-friendly Ruby code compiler
#
# 設計:
# - ビルド時 (CRuby) に走る
# - 出力は Spinel が AOT-compile できる pure Ruby
# - eval / binding / +""/.freeze / <<  を使わない
#
# 文法対応:
#   literal text        -> _out = _out + "..."
#   <%= expr %>         -> _out = _out + (expr).to_s
#   <%   code %>        -> code (raw)
#   <%# comment %>      -> skip
#   <%- ... %>          -> trim leading newline of preceding literal
#   <% ... -%>          -> trim trailing newline of following literal

module SpnlErb
  VERSION = "0.1.0"

  # Compile ERB string to Spinel-friendly Ruby body (no class wrapper).
  def self.compile_body(template, var_name: "_out")
    tokens = tokenize(template)
    emit_body(tokens, var_name)
  end

  # Compile to a complete class. ivars in template come from `attrs`.
  #
  #   compile_class(tpl, class_name: "UsersIndexView", attrs: ["name", "items"])
  #
  # 出力例:
  #   class UsersIndexView
  #     def initialize(name, items)
  #       @name = name; @items = items
  #     end
  #     def render
  #       _out = ""
  #       _out = _out + "..."
  #       _out
  #     end
  #   end
  def self.compile_class(template, class_name:, attrs: [], method_name: "render")
    body = compile_body(template)

    init_params = attrs.join(", ")
    init_assigns = attrs.map { |a| "      @#{a} = #{a}" }.join("\n")

    indented_body = body.split("\n").map { |l| "    " + l }.join("\n")

    <<~RUBY
      # AUTO-GENERATED by spnl-erb — DO NOT EDIT
      class #{class_name}
        def initialize(#{init_params})
      #{init_assigns}
        end

        def #{method_name}
      #{indented_body}
        end
      end
    RUBY
  end

  # --- 内部: tokenizer ---

  TOK_LITERAL = :lit
  TOK_EXPR    = :expr
  TOK_CODE    = :code

  def self.tokenize(template)
    tokens = []
    i = 0
    n = template.length

    while i < n
      open_idx = template.index("<%", i)
      if open_idx.nil?
        tokens << [TOK_LITERAL, template[i..-1]]
        break
      end

      # literal までを emit
      if open_idx > i
        tokens << [TOK_LITERAL, template[i...open_idx]]
      end

      # tag 判定
      tag_start = open_idx + 2
      kind = TOK_CODE
      trim_left = false
      trim_right = false

      case template[tag_start]
      when "="
        kind = TOK_EXPR
        tag_start += 1
      when "#"
        kind = :comment
        tag_start += 1
      when "-"
        trim_left = true
        tag_start += 1
      end

      close_idx = template.index("%>", tag_start)
      raise "unclosed ERB tag at #{open_idx}" if close_idx.nil?

      content_end = close_idx
      if template[close_idx - 1] == "-"
        trim_right = true
        content_end = close_idx - 1
      end

      content = template[tag_start...content_end].strip

      if kind == TOK_EXPR
        tokens << [TOK_EXPR, content]
      elsif kind == TOK_CODE
        tokens << [TOK_CODE, content]
      end

      i = close_idx + 2

      # trim_right: 直後の literal の先頭改行を削る
      if trim_right && i < n && template[i] == "\n"
        i += 1
      end

      # trim_left: 直前の literal token の末尾改行を削る
      if trim_left && !tokens.empty? && tokens.last && tokens.last[0] == TOK_LITERAL
        prev = tokens.last[1]
        if prev.end_with?("\n")
          tokens.last[1] = prev.chomp
        end
      end
    end

    tokens
  end

  def self.emit_body(tokens, var = "_out")
    lines = ["#{var} = \"\""]
    tokens.each do |kind, content|
      case kind
      when TOK_LITERAL
        next if content.empty?
        lines << "#{var} = #{var} + #{content.inspect}"
      when TOK_EXPR
        lines << "#{var} = #{var} + (#{content}).to_s"
      when TOK_CODE
        lines << content
      end
    end
    lines << var
    lines.join("\n")
  end
end
